# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'PiDou' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PiDou

  target 'PiDouTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PiDouUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'MJExtension'
pod 'MJRefresh'
#pod 'SDWebImage'
pod 'SDWebImage', '~> 4.3.0'
pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'Masonry'
pod 'BGFMDB', '~> 2.0.9'
pod 'FDFullscreenPopGesture', '1.1'
pod 'VODUpload'
end
